[package]
edition = "2021"
name = "data_munch"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2"
rand = "0.8.5"
serde = {version = "1", features = ["derive"]}
vinyana = "0.1.0"
